### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by pboling** [galtzo-floss/seed_migration#69]
@pjambet we use this gem extensively at @rivierapartners.

I'm interested in taking over the gem's maintenance.

@harrystech - if you are no longer using the gem, would you consider passing it to a new home?

**Comment by jclr** [comment]
@pboling I apologize for the delay in response here. I'm transferring ownership to @rivierapartners now.

**Comment by jclr** [comment]
@pboling turns out I don't have the permissions to do that. I'm still happy to transfer ownership to your account, if that works, and then you can do with it what you will. 

Before I do that, however, I did realize that we still do depend on the gem being publicly accessible. Will you be able to keep it available on RubyGems?

**Comment by pjambet** [comment]
@jclr Let me know if I can help, I guess I can either transfer ownership of the gem on rubygems to you or directly to @pboling

**Comment by jclr** [comment]
Thanks, @pjambet. Maybe you could transfer the ownership to me and I can take care of any further transfers.

**Comment by pboling** [comment]
I don't have any intentions to change any licensing or availability.  I publish all my gems on RubyGems.org :)

**Comment by jclr** [comment]
@pboling I have transferred ownership.

@pjambet you can transfer the RubyGems ownership directly to @pboling. Thanks!

**Comment by pboling** [comment]
@pjambet @irubnich @blahblahblah- Please add me as an owner on Rubygems

**Comment by pboling** [comment]
@jclr I am still not an admin on this repo.  What did you mean when you said you transferred ownership?

**Comment by pjambet** [comment]
@pboling Apologies for not doing back then, but just added you now. @jclr I tried to add you but I don't know what your RubyGems handle is

**Comment by pjambet** [comment]
@jclr Well, I have no idea how I didn't find you earlier then 🤦‍♂️ but anyway, you're also an owner too on Rubygems, just in case.

**Comment by jclr** [comment]
Might have something to do with the fact that I just created my account 😉

**Comment by jclr** [comment]
I just re-issued the transfer. Hopefully it works this time.

**Comment by pboling** [comment]
Worked!
