### ISSUE TITLE
Seed Migrations execute in what order?

### ISSUE THREAD

**Issue by JehandadK** [galtzo-floss/seed_migration#8]
Does seed migrations handles schema changes correctly? For e.g
1- Migration = id,name
2- Seed Migration = 1, English
3- Migration = id, name, script(required=true)
4- Seed Migration = 2, French, Francias

So if I migrate in production both migrations will execute before seeding? Will step 2 fail?

**Comment by jasantunes** [comment]
I know this is an old topic, but in case someone comes across this page, here's my solution:
A rake task that runs both schema and seeds migrations in chronological order:
https://gist.github.com/jasantunes/f1cecc87ad5901c7743b0b09c51817ef
